version: "3.3"
services: 
    jupyter:
        build: .
        ports:
          - "8080:8080"
        volumes: 
            - C:\Users\Hall\Desktop\JupyterDocker\jovyan:/home/jovyan/work:Z
        command: jupyter lab --ip 0.0.0.0 --port 8080
        working_dir: /home/jovyan/work
