version: "3.3"
services: 
    jupyter:
        build: .
        container_name: jupyter
        links:
          - "db:database"
        ports:
          - "8080:8080"
        volumes: 
            - C:\Users\Hall\Desktop\JupyterDocker\jovyan:/home/jovyan/work:Z
        command: jupyter lab --ip 0.0.0.0 --port 8080
        working_dir: /home/jovyan/work
        environment: 
          - LD_LIBRARY_PATH=/home/jovyan/instantclient_19_9
    db:
      image: mcr.microsoft.com/mssql/server
      hostname: sql1
      container_name: sql1
      ports:
        - "1433:1433"
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=p@ssw0rd